# Generated by Django 5.0.1 on 2024-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
