# Generated by Django 5.0.1 on 2024-01-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0002_lens_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='image',
        ),
    ]
