# Generated by Django 5.0.1 on 2024-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0003_remove_lens_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
