# Generated by Django 5.0.1 on 2024-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0004_lens_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='title',
        ),
        migrations.AlterField(
            model_name='lens',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
